Fix loading button popping
MNewbigging/wordbash pull request #3
Opened 2021-09-09 09:31 UTC by elsalindholm

Home screen loading and pay button have been combined into one button that changes its content/properties depending on whether the app is loading or not.

The loading button should:
- say 'loading'
- have the same size & style as the play button
- have no hover effects
- not do anything onClick
- not disappear once loading has finished

2021-09-09 09:38 UTC, MNewbigging commented on src/components/common/button/Button.tsx
> +interface ButtonProps {
some small changes to the props:

- rename onPlay to onClick
- exiting and loading should be optional
- add a className: string property - this gets added to the hardcoded 'button' classname in the comp

2021-09-09 09:39 UTC, MNewbigging commented on src/components/common/button/Button.tsx
> +    const buttonText = loading ? 'loading' : 'play';
'text' should be a prop for this button - so the button display the given text unless it's loading, in which case it always just says loading

2021-09-09 09:41 UTC, MNewbigging requested changes

2021-09-09 09:41 UTC, MNewbigging commented on src/components/common/button/button.scss
> +  &.play {
can't call this play! rename to something more generic

2021-09-09 09:41 UTC, MNewbigging commented on src/components/web/home/HomeScreenWeb.tsx
>  import { LetterStatus } from '../../../model/Letter';
put a space below react import

2021-09-09 09:41 UTC, MNewbigging commented on src/components/common/button/button.scss
> +  width: 300px;
button sizes cannot be in the generic styles, they must be in the component-style file that creates the button!

2021-09-09 13:29 UTC, elsalindholm commented
Requested changes made, hopefully correctly!

2021-09-10 10:06 UTC, MNewbigging commented on src/components/common/button/Button.tsx
> +    const buttonClass = loading ? 'loading' : className;
you'd want to apply the given class name at all times, regardless of loading - custom class names should control things like width/height, which shouldn't change with loading

2021-09-10 10:07 UTC, MNewbigging commented on src/components/web/home/home-screen-web.scss
> +  .button {
revert this to 'play'! this is your custom classname for the button, so should style against that

2021-09-10 10:09 UTC, MNewbigging commented on src/components/web/home/home-screen-web.scss
> +    &.loading {
by doing this outside the button.scss, it means you'll have to do it again for every button that loads. What to do is:

- in Button.tsx, apply a className 'loading' if you're loading (you're kind of doing this, but shouldn't prevent their custom classname from being added, so make it a separate line)
- then in button.scss, you can say the above; if loading, don't do hover styles

2021-09-10 10:09 UTC, MNewbigging commented on src/components/web/home/home-screen-web.scss
> +    &.play {
once you've renamed the above classname to 'play' from 'button' you can lose the top &.play here and just have the hover stuff inside

2021-09-10 10:09 UTC, MNewbigging commented on src/components/web/home/home-screen-web.scss
> +      &.exiting {
put spaces above nested blocks like this!

2021-09-13 10:13 UTC, elsalindholm commented
Please could you merge thsi request when you have a moment? :)

2021-09-13 10:16 UTC, MNewbigging approved these changes

2021-09-13 10:16 UTC, merged